"""Wrapper for PlatformIO build and espota.py upload commands."""

from __future__ import annotations

import asyncio
import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING, AsyncIterator

if TYPE_CHECKING:
    from asyncio.subprocess import Process


@dataclass
class FirmwareInfo:
    """Information about the built firmware."""

    path: Path
    version: str  # GIT_COMMIT_HASH from version.h
    date: str  # GIT_COMMIT_DATE from version.h


# OTA password from platformio.ini upload_flags
OTA_PASSWORD = "kinetic-mirror-ota"
OTA_PORT = 3232


class PioWrapper:
    """Wrapper for PlatformIO build and espota.py upload operations."""

    def __init__(self, env: str, project_dir: Path | None = None):
        self.env = env
        self.project_dir = project_dir or Path.cwd()
        # espota.py progress pattern: "Uploading: [====     ] 45%"
        self.progress_pattern = re.compile(r"]\s*(\d+)%")

    async def build(self, log_file: Path | None = None) -> FirmwareInfo:
        """Build firmware and return info.

        Args:
            log_file: Optional path to write build output

        Returns:
            FirmwareInfo with path, version, and date
        """
        cmd = ["pio", "run", "-e", self.env]
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
            cwd=self.project_dir,
        )

        output = await self._capture_output(proc, log_file, cmd)

        if proc.returncode != 0:
            raise RuntimeError(f"Build failed with code {proc.returncode}\n{output}")

        return await self.get_firmware_info()

    async def get_firmware_info(self) -> FirmwareInfo:
        """Extract firmware version and date from built artifacts."""
        # Read version.h generated by inject_version.py
        version_h = self.project_dir / "include" / "version.h"
        if not version_h.exists():
            raise FileNotFoundError("version.h not found; run build first")

        content = version_h.read_text()
        version_match = re.search(r'#define GIT_COMMIT_HASH "(.+?)"', content)
        date_match = re.search(r'#define GIT_COMMIT_DATE "(.+?)"', content)

        if not version_match or not date_match:
            raise ValueError("Could not parse version.h")

        firmware_path = self.project_dir / ".pio" / "build" / self.env / "firmware.bin"
        if not firmware_path.exists():
            raise FileNotFoundError(f"Firmware binary not found: {firmware_path}")

        return FirmwareInfo(
            path=firmware_path,
            version=version_match.group(1),
            date=date_match.group(1),
        )

    def _find_espota(self) -> Path:
        """Find espota.py in PlatformIO packages."""
        espota_path = (
            self.project_dir
            / ".pio"
            / "packages"
            / "framework-arduinoespressif32"
            / "tools"
            / "espota.py"
        )
        if not espota_path.exists():
            raise FileNotFoundError(
                f"espota.py not found at {espota_path}. "
                "Run 'pio run -e esp32DedicatedStep' first to install packages."
            )
        return espota_path

    async def upload(self, ip: str, log_file: Path, firmware_path: Path) -> AsyncIterator[int]:
        """Upload firmware via OTA using espota.py directly.

        This bypasses PlatformIO's build system to avoid rebuilding,
        which prevents version.h regeneration and parallel build races.

        Args:
            ip: Device IP address
            log_file: Path to write upload output
            firmware_path: Path to firmware.bin file

        Yields:
            Progress percentage (0-100)
        """
        espota = self._find_espota()

        cmd = [
            "python3",
            str(espota),
            "-r",  # show progress bar output
            "-d",  # debug output
            "-i",
            ip,
            "-p",
            str(OTA_PORT),
            "-a",
            OTA_PASSWORD,
            "-f",
            str(firmware_path),
        ]

        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
            cwd=self.project_dir,
        )

        last_percent = 0
        with open(log_file, "wb") as log:
            # Write command header
            header = f"# Command: {' '.join(cmd)}\n# Started: {datetime.now().isoformat()}\n\n"
            log.write(header.encode())
            log.flush()

            assert proc.stdout is not None
            buffer = ""
            while True:
                # Read chunks instead of lines - espota.py uses \r for progress
                chunk = await proc.stdout.read(256)
                if not chunk:
                    break

                log.write(chunk)
                log.flush()

                # Decode and accumulate for pattern matching
                buffer += chunk.decode("utf-8", errors="ignore")

                # Parse progress percentage from "Uploading: [====     ] 45%"
                # Look for all matches in buffer
                for match in self.progress_pattern.finditer(buffer):
                    percent = int(match.group(1))
                    if percent > last_percent:
                        last_percent = percent
                        yield percent

                # Keep only recent buffer to avoid memory growth
                if len(buffer) > 1024:
                    buffer = buffer[-512:]

        await proc.wait()
        if proc.returncode != 0:
            raise RuntimeError(f"Upload failed (exit {proc.returncode})")

        yield 100

    async def _capture_output(
        self, proc: Process, log_file: Path | None, cmd: list[str] | None = None
    ) -> str:
        """Capture process output, optionally writing to log file."""
        assert proc.stdout is not None
        output_lines: list[bytes] = []

        async def read_lines(log_handle: object | None) -> None:
            while True:
                line = await proc.stdout.readline()  # type: ignore[union-attr]
                if not line:
                    break
                output_lines.append(line)
                if log_handle:
                    log_handle.write(line)  # type: ignore[union-attr]
                    log_handle.flush()  # type: ignore[union-attr]

        if log_file:
            with open(log_file, "wb") as log_handle:
                # Write command header
                if cmd:
                    header = (
                        f"# Command: {' '.join(cmd)}\n# Started: {datetime.now().isoformat()}\n\n"
                    )
                    log_handle.write(header.encode())
                    log_handle.flush()
                await read_lines(log_handle)
        else:
            await read_lines(None)

        await proc.wait()
        return b"".join(output_lines).decode("utf-8", errors="ignore")
