"""
PlatformIO pre-build script to inject git version information.
Generates include/version.h with commit hash and timestamp.

This script runs at import time (before library compilation) to ensure
version.h is available when libraries that include it are compiled.
"""

from __future__ import annotations

import os
import subprocess
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:

    def Import(*args: Any, **kwargs: Any) -> None: ...

    env: Any

Import("env")


def get_git_info() -> tuple[str, str]:
    """Extract git commit hash and commit date."""
    try:
        # Get commit hash (short, 7 chars)
        commit_hash = subprocess.check_output(
            ["git", "rev-parse", "--short=7", "HEAD"],
            stderr=subprocess.STDOUT,
            text=True,
        ).strip()

        # Get commit timestamp (ISO 8601 format)
        commit_date = subprocess.check_output(
            ["git", "show", "-s", "--format=%cI", "HEAD"],
            stderr=subprocess.STDOUT,
            text=True,
        ).strip()

        # Check if working tree is dirty
        status = subprocess.check_output(
            ["git", "status", "--porcelain"],
            stderr=subprocess.STDOUT,
            text=True,
        ).strip()

        if status:
            commit_hash += "-dirty"
            # Use current build timestamp for dirty builds (commit timestamp is stale)
            commit_date = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S%z")

        return commit_hash, commit_date

    except (subprocess.CalledProcessError, FileNotFoundError):
        # Fallback if git is not available
        return "unknown", "unknown"


def generate_version_header() -> None:
    """Generate version.h header file."""
    print("*** Injecting version information ***")

    project_dir = env.get("PROJECT_DIR")
    version_file = os.path.join(project_dir, "include", "version.h")

    commit_hash, commit_date = get_git_info()

    print(f"  Git Commit: {commit_hash}")
    print(f"  Commit Date: {commit_date}")

    header_content = f'''// Auto-generated by tools/inject_version.py
// DO NOT EDIT MANUALLY

#pragma once

// NOLINTBEGIN(cppcoreguidelines-macro-usage)
#define GIT_COMMIT_HASH "{commit_hash}"
#define GIT_COMMIT_DATE "{commit_date}"
// NOLINTEND(cppcoreguidelines-macro-usage)
'''

    # Only write if content changed (avoid unnecessary rebuilds)
    write_file = True
    if os.path.exists(version_file):
        with open(version_file) as f:
            if f.read() == header_content:
                write_file = False

    if write_file:
        os.makedirs(os.path.dirname(version_file), exist_ok=True)
        with open(version_file, "w") as f:
            f.write(header_content)
        print(f"  Generated: {version_file}")
    else:
        print(f"  Unchanged: {version_file}")

    print("*** Version injection complete ***")


# Generate version.h immediately at script load time
# This ensures it's available before any library compilation
generate_version_header()
